In [1]:
import pandas as pd

In [16]:
# Load Mercari Dataset
df = pd.read_csv(r"D:\Career\Projects\mercari-price-analysis\data\train.tsv", sep="\t")

# Data Greetings

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1482535 entries, 0 to 1482534
Data columns (total 8 columns):
 #   Column             Non-Null Count    Dtype
---  ------             --------------    -----
 0   train_id           1482535 non-null  int64
 1   name               1482535 non-null  object
 2   item_condition_id  1482535 non-null  int64
 3   category_name      1476208 non-null  object
 4   brand_name         849853 non-null   object
 5   price              1482535 non-null  float64
 6   shipping           1482535 non-null  int64
 7   item_description   1482529 non-null  object
dtypes: float64(1), int64(3), object(4)
memory usage: 90.5+ MB

In [18]:
# First Look -
df.shape  # (rows, cols)

(1482535, 8)

In [19]:
df.head()  # First 5 rows

,train_id,name,item_condition_id,category_name,brand_name,price,shipping,item_description
0,0,MLB Cincinnati Reds T Shirt Size XL,3,Men/Tops/T-shirts,NaN,10.0,1,No description yet
1,1,Razer BlackWidow Chroma Keyboard,3,Electronics/Computers & Tablets/Components & P...,Razer,52.0,0,This keyboard is in great condition and works ...
2,2,AVA-VIV Blouse,1,Women/Tops & Blouses/Blouse,Target,10.0,1,Adorable top with a hint of lace and a key hol...
3,3,Leather Horse Statues,1,Home/Home Décor/Home Décor Accents,NaN,35.0,1,New with tags. Leather horses. Retail for [rm]...
4,4,24K GOLD plated rose,1,Women/Jewelry/Necklaces,NaN,44.0,0,Complete with certificate of authenticity

In [20]:
df.info()   # dtypes + null counts

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1482535 entries, 0 to 1482534
Data columns (total 8 columns):
 #   Column             Non-Null Count    Dtype
---  ------             --------------    -----
 0   train_id           1482535 non-null  int64
 1   name               1482535 non-null  object
 2   item_condition_id  1482535 non-null  int64
 3   category_name      1476208 non-null  object
 4   brand_name         849853 non-null   object
 5   price              1482535 non-null  float64
 6   shipping           1482535 non-null  int64
 7   item_description   1482529 non-null  object
dtypes: float64(1), int64(3), object(4)
memory usage: 90.5+ MB

In [21]:
df.describe()    # Stats for numeric cols

           train_id  item_condition_id         price      shipping
count  1.482535e+06       1.482535e+06  1.482535e+06  1.482535e+06
mean   7.412670e+05       1.907380e+00  2.673752e+01  4.472744e-01
std    4.279711e+05       9.031586e-01  3.858607e+01  4.972124e-01
min    0.000000e+00       1.000000e+00  0.000000e+00  0.000000e+00
25%    3.706335e+05       1.000000e+00  1.000000e+01  0.000000e+00
50%    7.412670e+05       2.000000e+00  1.700000e+01  0.000000e+00
75%    1.111900e+06       3.000000e+00  2.900000e+01  1.000000e+00
max    1.482534e+06       5.000000e+00  2.009000e+03  1.000000e+00

In [22]:
df.isnull().sum() / len(df)*100   # null counts in %

train_id              0.000000
name                  0.000000
item_condition_id     0.000000
category_name         0.426769
brand_name           42.675687
price                 0.000000
shipping              0.000000
item_description      0.000405
dtype: float64

# loc & iloc

In [23]:
# Get rows 100 to 109 using iloc
df.iloc[100:110]

,train_id,name,item_condition_id,category_name,brand_name,price,shipping,item_description
100,100,Muscle t-shirt,3,Women/Tops & Blouses/T-Shirts,NaN,12.0,0,What goes better with summer than tacos & tequ...
101,101,Rock Revival 24 Bootcut,3,Women/Jeans/Boot Cut,Rock Revival,66.0,0,Any questions please ask! Price is firm
102,102,Black Boho Floral Embroidered Maxi Dress,2,Women/Dresses/Knee-Length,NaN,29.0,0,Size medium in perfect condition
103,103,kids adidas,1,Kids/Boys 2T-5T/Shoes,NaN,36.0,0,size 13 Kids brand new. paid [rm] FIRM ON THE ...
104,104,Picture frame,2,Home/Home Décor/Home Décor Accents,NaN,14.0,0,Everything is in perfect condition Tags: heave...
105,105,Leather Fossil Wallet,3,Women/Women's Accessories/Wallets,Fossil,10.0,0,"Genuine leather, good preowned condition, does..."
106,106,Floral two Piece tracksuit set,1,Women/Athletic Apparel/Tracksuits & Sweats,Adidas,41.0,1,Cute boutique brand suit. Floral Print . Polye...
107,107,Boots NWT 6.5,1,Women/Shoes/Boots,Merona,13.0,1,Merona short boot new with tag size 6.5 come j...
108,108,New Duck Boots sz.7.5,1,Women/Shoes/Boots,Boulevard Boutique,38.0,0,New Duck Boots Sz.7.5 Stock up on These Trendy...
109,109,Rose Gold Necklace with Silver Studs,2,Women/Jewelry/Necklaces,NaN,16.0,0,Brand New

In [24]:
# Get The item name and price of row 250 using iloc 
df.iloc[250, 1]

'Lularoe chevron tie dye Sarah'

In [28]:
# Get all items where price > 100, show only name, price, brand_name
df.loc[df["price"] > 100, ["name", "price", "brand_name"]]

                                     name  price        brand_name
22         Galaxy S7 Edge (Unlocked) 32GB  386.0           Samsung
36                           Black bag 30  209.0               NaN
38                               XBOX One  226.0              Xbox
50                 Michael Kors CrossBody  114.0      Michael Kors
60        1/4 ct Diamond Engagement Ring!  119.0               NaN
...                                   ...    ...               ...
1482364       Kate Spade Large Hayden Bag  191.0        Kate Spade
1482375  Beats By Dre Studio Wireless MCM  225.0  Beats by Dr. Dre
1482387            IPAD PRO 8.7 INCH 32GB  509.0             Apple
1482499                         iPhone 7+  400.0             Apple
1482506        KitchenAid 4.5 quart mixer  165.0        KitchenAid

[41892 rows x 3 columns]

In [30]:
# Get all electronics where shipping == 1
df.loc[(df["category_name"].str.startswith("Electronics")) & (df["shipping"] == 1)]

,train_id,name,item_condition_id,category_name,brand_name,price,shipping,item_description
23,23,Triple car charger,1,Electronics/Cell Phones & Accessories/Chargers...,NaN,8.0,1,Brand new never used All colors are available ...
26,26,Otterbox Defender iPhone 6 Plus/6s Plus,1,"Electronics/Cell Phones & Accessories/Cases, C...",Apple,13.0,1,Brand new Otterbox Defender iPhone 6 Plus/6s Plus
59,59,HV-900 sports Bluetooth headset,1,Electronics/Cell Phones & Accessories/Headsets,NaN,12.0,1,New HV-900 sports sweatproof wireless Bluetoot...
69,69,Iphone 6/6s marble design case,1,"Electronics/Cell Phones & Accessories/Cases, C...",NaN,5.0,1,❕PLEASE CHECK SIZE BEFORE ORDERING❕ ❕❕❕IF YOU ...
97,97,iPhone 5S Mickey ear case,2,"Electronics/Cell Phones & Accessories/Cases, C...",NaN,9.0,1,Bling Mickey ear case!! Just used one for a Di...
...,...,...,...,...,...,...,...,...
1482493,1482493,Horizon Zero Dawn Ps4,1,Electronics/Video Games & Consoles/Games,NaN,38.0,1,GAME IS BRAND NEW FACTORY SEALED **YES IT IS A...
1482495,1482495,XBOX Bundle,3,Electronics/Video Games & Consoles/Games,Xbox,25.0,1,2 XBOX games Call of duty and Halo
1482499,1482499,iPhone 7+,2,Electronics/Cell Phones & Accessories/Cell Pho...,Apple,400.0,1,For Serena
1482510,1482510,2×Popsockets for all phone & Tablet,1,Electronics/Cell Phones & Accessories/Cell Pho...,NaN,9.0,1,Popsockets for all phone & Tablet Add 1 clip m...
1482522,1482522,LG K7/Tribute 5 Hybrid Case,1,"Electronics/Cell Phones & Accessories/Cases, C...",NaN,8.0,1,"Perfect Design for LG Tribute 5 / LG K7, NOT f..."

In [ ]:
# How Many items h