In [1]:
import pandas as pd

In [2]:
# Load Mercari Dataset
df = pd.read_csv(r"D:\Career\Projects\mercari-price-analysis\data\train.tsv", sep="\t")

# Data Greetings

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1482535 entries, 0 to 1482534
Data columns (total 8 columns):
 #   Column             Non-Null Count    Dtype
---  ------             --------------    -----
 0   train_id           1482535 non-null  int64
 1   name               1482535 non-null  object
 2   item_condition_id  1482535 non-null  int64
 3   category_name      1476208 non-null  object
 4   brand_name         849853 non-null   object
 5   price              1482535 non-null  float64
 6   shipping           1482535 non-null  int64
 7   item_description   1482529 non-null  object
dtypes: float64(1), int64(3), object(4)
memory usage: 90.5+ MB

In [4]:
# First Look -
df.shape  # (rows, cols)

(1482535, 8)

In [5]:
df.head()  # First 5 rows

,train_id,name,item_condition_id,category_name,brand_name,price,shipping,item_description
0,0,MLB Cincinnati Reds T Shirt Size XL,3,Men/Tops/T-shirts,NaN,10.0,1,No description yet
1,1,Razer BlackWidow Chroma Keyboard,3,Electronics/Computers & Tablets/Components & P...,Razer,52.0,0,This keyboard is in great condition and works ...
2,2,AVA-VIV Blouse,1,Women/Tops & Blouses/Blouse,Target,10.0,1,Adorable top with a hint of lace and a key hol...
3,3,Leather Horse Statues,1,Home/Home Décor/Home Décor Accents,NaN,35.0,1,New with tags. Leather horses. Retail for [rm]...
4,4,24K GOLD plated rose,1,Women/Jewelry/Necklaces,NaN,44.0,0,Complete with certificate of authenticity

In [6]:
df.info()   # dtypes + null counts

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1482535 entries, 0 to 1482534
Data columns (total 8 columns):
 #   Column             Non-Null Count    Dtype
---  ------             --------------    -----
 0   train_id           1482535 non-null  int64
 1   name               1482535 non-null  object
 2   item_condition_id  1482535 non-null  int64
 3   category_name      1476208 non-null  object
 4   brand_name         849853 non-null   object
 5   price              1482535 non-null  float64
 6   shipping           1482535 non-null  int64
 7   item_description   1482529 non-null  object
dtypes: float64(1), int64(3), object(4)
memory usage: 90.5+ MB

In [7]:
df.describe()    # Stats for numeric cols

           train_id  item_condition_id         price      shipping
count  1.482535e+06       1.482535e+06  1.482535e+06  1.482535e+06
mean   7.412670e+05       1.907380e+00  2.673752e+01  4.472744e-01
std    4.279711e+05       9.031586e-01  3.858607e+01  4.972124e-01
min    0.000000e+00       1.000000e+00  0.000000e+00  0.000000e+00
25%    3.706335e+05       1.000000e+00  1.000000e+01  0.000000e+00
50%    7.412670e+05       2.000000e+00  1.700000e+01  0.000000e+00
75%    1.111900e+06       3.000000e+00  2.900000e+01  1.000000e+00
max    1.482534e+06       5.000000e+00  2.009000e+03  1.000000e+00

In [8]:
df.isnull().sum() / len(df)*100   # null counts in %

train_id              0.000000
name                  0.000000
item_condition_id     0.000000
category_name         0.426769
brand_name           42.675687
price                 0.000000
shipping              0.000000
item_description      0.000405
dtype: float64

# loc & iloc

In [9]:
# Get rows 100 to 109 using iloc
df.iloc[100:110]

,train_id,name,item_condition_id,category_name,brand_name,price,shipping,item_description
100,100,Muscle t-shirt,3,Women/Tops & Blouses/T-Shirts,NaN,12.0,0,What goes better with summer than tacos & tequ...
101,101,Rock Revival 24 Bootcut,3,Women/Jeans/Boot Cut,Rock Revival,66.0,0,Any questions please ask! Price is firm
102,102,Black Boho Floral Embroidered Maxi Dress,2,Women/Dresses/Knee-Length,NaN,29.0,0,Size medium in perfect condition
103,103,kids adidas,1,Kids/Boys 2T-5T/Shoes,NaN,36.0,0,size 13 Kids brand new. paid [rm] FIRM ON THE ...
104,104,Picture frame,2,Home/Home Décor/Home Décor Accents,NaN,14.0,0,Everything is in perfect condition Tags: heave...
105,105,Leather Fossil Wallet,3,Women/Women's Accessories/Wallets,Fossil,10.0,0,"Genuine leather, good preowned condition, does..."
106,106,Floral two Piece tracksuit set,1,Women/Athletic Apparel/Tracksuits & Sweats,Adidas,41.0,1,Cute boutique brand suit. Floral Print . Polye...
107,107,Boots NWT 6.5,1,Women/Shoes/Boots,Merona,13.0,1,Merona short boot new with tag size 6.5 come j...
108,108,New Duck Boots sz.7.5,1,Women/Shoes/Boots,Boulevard Boutique,38.0,0,New Duck Boots Sz.7.5 Stock up on These Trendy...
109,109,Rose Gold Necklace with Silver Studs,2,Women/Jewelry/Necklaces,NaN,16.0,0,Brand New

In [10]:
# Get The item name and price of row 250 using iloc 
df.iloc[250, 1]

'Lularoe chevron tie dye Sarah'

In [11]:
# Get all items where price > 100, show only name, price, brand_name
df.loc[df["price"] > 100, ["name", "price", "brand_name"]]

                                     name  price        brand_name
22         Galaxy S7 Edge (Unlocked) 32GB  386.0           Samsung
36                           Black bag 30  209.0               NaN
38                               XBOX One  226.0              Xbox
50                 Michael Kors CrossBody  114.0      Michael Kors
60        1/4 ct Diamond Engagement Ring!  119.0               NaN
...                                   ...    ...               ...
1482364       Kate Spade Large Hayden Bag  191.0        Kate Spade
1482375  Beats By Dre Studio Wireless MCM  225.0  Beats by Dr. Dre
1482387            IPAD PRO 8.7 INCH 32GB  509.0             Apple
1482499                         iPhone 7+  400.0             Apple
1482506        KitchenAid 4.5 quart mixer  165.0        KitchenAid

[41892 rows x 3 columns]

In [12]:
# Get all electronics where shipping == 1
df.loc[(df["category_name"].str.startswith("Electronics")) & (df["shipping"] == 1)]

,train_id,name,item_condition_id,category_name,brand_name,price,shipping,item_description
23,23,Triple car charger,1,Electronics/Cell Phones & Accessories/Chargers...,NaN,8.0,1,Brand new never used All colors are available ...
26,26,Otterbox Defender iPhone 6 Plus/6s Plus,1,"Electronics/Cell Phones & Accessories/Cases, C...",Apple,13.0,1,Brand new Otterbox Defender iPhone 6 Plus/6s Plus
59,59,HV-900 sports Bluetooth headset,1,Electronics/Cell Phones & Accessories/Headsets,NaN,12.0,1,New HV-900 sports sweatproof wireless Bluetoot...
69,69,Iphone 6/6s marble design case,1,"Electronics/Cell Phones & Accessories/Cases, C...",NaN,5.0,1,❕PLEASE CHECK SIZE BEFORE ORDERING❕ ❕❕❕IF YOU ...
97,97,iPhone 5S Mickey ear case,2,"Electronics/Cell Phones & Accessories/Cases, C...",NaN,9.0,1,Bling Mickey ear case!! Just used one for a Di...
...,...,...,...,...,...,...,...,...
1482493,1482493,Horizon Zero Dawn Ps4,1,Electronics/Video Games & Consoles/Games,NaN,38.0,1,GAME IS BRAND NEW FACTORY SEALED **YES IT IS A...
1482495,1482495,XBOX Bundle,3,Electronics/Video Games & Consoles/Games,Xbox,25.0,1,2 XBOX games Call of duty and Halo
1482499,1482499,iPhone 7+,2,Electronics/Cell Phones & Accessories/Cell Pho...,Apple,400.0,1,For Serena
1482510,1482510,2×Popsockets for all phone & Tablet,1,Electronics/Cell Phones & Accessories/Cell Pho...,NaN,9.0,1,Popsockets for all phone & Tablet Add 1 clip m...
1482522,1482522,LG K7/Tribute 5 Hybrid Case,1,"Electronics/Cell Phones & Accessories/Cases, C...",NaN,8.0,1,"Perfect Design for LG Tribute 5 / LG K7, NOT f..."

In [13]:
# How Many items have price == 0? 
df.loc[df["price"] == 0].shape[0]

874

# Data Cleaning

In [14]:
print("Shape before cleaning:", df.shape)

Shape before cleaning: (1482535, 8)

In [15]:
print("\nNull %:\n", (df.isnull().sum() / len(df) * 100).round(2))

Null %:
 train_id              0.00
name                  0.00
item_condition_id     0.00
category_name         0.43
brand_name           42.68
price                 0.00
shipping              0.00
item_description      0.00
dtype: float64

In [16]:
# Drop Rows where category_name is null (only 0.43% = safe to drop)
df = df.dropna(subset=["category_name"])
print("\nAfter dropping null categories:", df.shape)

After dropping null categories: (1476208, 8)

In [17]:
# Fill Brand_name nulls with "No Brand" (43% Data - Never Drop)
df["brand_name"] = df["brand_name"].fillna("No brand")

In [18]:
# Check for duplicates
df.duplicated().sum()

np.int64(0)

In [19]:
# Check price = 0 rows - are these real?
print("\nItems with price = 0:")
df[df["price"] == 0][["name", "category_name", "brand_name"]].head(10)

Items with price = 0:

,name,category_name,brand_name
1325,Alabama Crimson Tide Quality Lanyard,Sports & Outdoors/Fan Shop/NCAA,No brand
2544,Levi leggings,"Women/Jeans/Slim, Skinny",Levi's®
2712,Simple Red Lace Lingerie Top,Women/Underwear/G-Strings & Thongs,No brand
3576,Turquoise 15 Pc Makeup Brush Set,Beauty/Tools & Accessories/Makeup Brushes & Tools,No brand
3761,Girls size 7/8,Kids/Girls (4+)/Tops & T-Shirts,No brand
5237,Nursing Bra,Women/Underwear/Bras,Motherhood Maternity
6175,"Multi Listing Bundled Package, Thanks",Electronics/Media/DVD,No brand
7116,Nike Dri-Fit High Power Speed Tights,"Women/Athletic Apparel/Pants, Tights, Leggings",Nike
7622,Hands free earpiece,Electronics/Cell Phones & Accessories/Headsets,No brand
10812,Vampire candy bowl,Home/Seasonal Décor/Halloween,No brand

In [20]:
# item description have some null lets drop them
df = df.dropna(subset=["item_description"])

In [21]:
# Verify Cleaning worked:
print(f"Null counts after cleaning: {df.isnull().sum()}")

Null counts after cleaning: train_id             0
name                 0
item_condition_id    0
category_name        0
brand_name           0
price                0
shipping             0
item_description     0
dtype: int64

# Featuring Engineerning

In [22]:
import numpy as np

In [23]:
# Extarct main_category and sub_category
df["main_category"] = df["category_name"].str.split("/").str[0]
df["sub_category"] = df["category_name"].str.split("/").str[1]

In [24]:
# Normalize brand_name to lowercase for consistent grouping
df["brand_name"] = df["brand_name"].str.lower().str.strip()

In [25]:
# has_description - is the description meaningful?
df["has_description"] = df["item_description"].apply(
    lambda x: 0 if x == "No description yet" else 1
)

In [26]:
# name_length - longer name might indicate more detail = higher price?
df["name_length"] = df["name"].str.len()

In [27]:
# Map condition to label
condition_map = {1: "New", 2: "Like New", 3: "Good", 4: "Fair", 5:"Poor"}
df["condition_label"] = df["item_condition_id"].map(condition_map)

 ------VERIFY----------------------------------------------

In [28]:
print(f"New Columns: {df.columns.tolist()}")

New Columns: ['train_id', 'name', 'item_condition_id', 'category_name', 'brand_name', 'price', 'shipping', 'item_description', 'main_category', 'sub_category', 'has_description', 'name_length', 'condition_label']

In [29]:
print("New columns:", df.columns.tolist())
print("\nmain_category value counts (top 10):\n", df["main_category"].value_counts().head(10))
print("\nhas_description distribution:\n", df["has_description"].value_counts())
print("\nSample of new features:\n", df[["name", "main_category", "sub_category", "condition_label", "has_description", "name_length"]].head(10))

New columns: ['train_id', 'name', 'item_condition_id', 'category_name', 'brand_name', 'price', 'shipping', 'item_description', 'main_category', 'sub_category', 'has_description', 'name_length', 'condition_label']

main_category value counts (top 10):
 main_category
Women                     664382
Beauty                    207827
Kids                      171688
Electronics               122689
Men                        93680
Home                       67871
Vintage & Collectibles     46530
Other                      45351
Handmade                   30842
Sports & Outdoors          25342
Name: count, dtype: int64

has_description distribution:
 has_description
1    1394335
0      81867
Name: count, dtype: int64

Sample of new features:
                                      name           main_category  \
0     MLB Cincinnati Reds T Shirt Size XL                     Men
1        Razer BlackWidow Chroma Keyboard             Electronics
2                          AVA-VIV Blouse                   Women
3                   Leather Horse Statues                    Home
4                    24K GOLD plated rose                   Women
5        Bundled items requested for Ruie                   Women
6      Acacia pacific tides santorini top                   Women
7    Girls cheer and tumbling bundle of 7       Sports & Outdoors
8                   Girls Nike Pro shorts       Sports & Outdoors
9  Porcelain clown doll checker pants VTG  Vintage & Collectibles

          sub_category condition_label  has_description  name_length
0                 Tops            Good                0           35
1  Computers & Tablets            Good                1           32
2       Tops & Blouses             New                1           14
3           Home Décor             New                1           21
4              Jewelry             New                1           20
5                Other            Good                1           32
6             Swimwear            Good                1           34
7              Apparel            Good                1           36
8              Apparel            Good                1           21
9         Collectibles            Good                1           38

# groupby & aggregation

--------GROUPBY ANALYSIS---------------------------------

In [36]:
# Avergae price per main_category - sorted descending
print("===  Avg Price by Category  ===")
df.groupby("main_category")["price"].mean().sort_values(ascending=False).round(2)

===  Avg Price by Category  ===

main_category
Electronics               35.17
Men                       34.71
Women                     28.89
Vintage & Collectibles    27.34
Sports & Outdoors         25.53
Home                      24.54
Other                     20.81
Kids                      20.64
Beauty                    19.67
Handmade                  18.16
Name: price, dtype: float64

In [37]:
# Item count per main_category
print("\n=== Item Count by Category ===")
df.groupby("main_category").size().sort_values(ascending=False)

=== Item Count by Category ===

main_category
Women                     664382
Beauty                    207827
Kids                      171688
Electronics               122689
Men                        93680
Home                       67871
Vintage & Collectibles     46530
Other                      45351
Handmade                   30842
Sports & Outdoors          25342
dtype: int64

In [44]:
# Full agg tabel - avg, count, max per category
print("\n========             Full Category Summary            ===========")
summary = df.groupby("main_category")["price"].agg(
    avg_price="mean",
    total_item="count",
    max_price="max",
    min_price="min"
).round(2).sort_values("avg_price", ascending=False)
summary

========             Full Category Summary            ===========

                        avg_price  total_item  max_price  min_price
main_category
Electronics                 35.17      122689     1909.0        0.0
Men                         34.71       93680     1309.0        0.0
Women                       28.89      664382     2009.0        0.0
Vintage & Collectibles      27.34       46530     1709.0        0.0
Sports & Outdoors           25.53       25342      915.0        0.0
Home                        24.54       67871      848.0        0.0
Other                       20.81       45351     1400.0        0.0
Kids                        20.64      171688      809.0        0.0
Beauty                      19.67      207827     2000.0        0.0
Handmade                    18.16       30842     1750.0        0.0

In [45]:
# Does shipping affect price?
print("\n=== Avg Price by Shipping ===")
df.groupby("shipping")["price"].mean().round(2)

=== Avg Price by Shipping ===

shipping
0    30.12
1    22.57
Name: price, dtype: float64

In [46]:
# Avg Price by Condition
print("\n=== Avg Price by Condition ===")
df.groupby("condition_label")["price"].mean().round(2).sort_values(ascending=False)

=== Avg Price by Condition ===

condition_label
Poor        31.75
Like New    27.58
Good        26.54
New         26.49
Fair        24.37
Name: price, dtype: float64

In [47]:
# Multi-column: avg price by category + shipping
print("===  Avg Price by Category + Shipping  ===")
df.groupby(["main_category", "shipping"])["price"].mean().sort_values(ascending=False).round(2)

===  Avg Price by Category + Shipping  ===

main_category           shipping
Electronics             0           47.78
Men                     0           36.14
Vintage & Collectibles  0           33.52
Men                     1           31.98
Women                   0           30.63
Sports & Outdoors       0           28.38
Home                    0           27.21
Electronics             1           26.20
Women                   1           26.18
Handmade                0           25.59
Other                   0           25.30
Beauty                  0           23.73
Kids                    0           23.18
Vintage & Collectibles  1           22.44
Sports & Outdoors       1           21.95
Home                    1           17.82
Beauty                  1           17.08
Kids                    1           16.98
Other                   1           16.92
Handmade                1           13.44
Name: price, dtype: float64

# merge & concat

In [48]:
# Create a category metadata table (simulating a second table)
cat_meta = pd.DataFrame({
    "main_category": ["Women", "Beauty", "Kids", "Electronics", 
                      "Men", "Home", "Vintage & Collectibles", 
                      "Other", "Handmade", "Sports & Outdoors"],
    "market_segment": ["Fashion", "Personal Care", "Family", "Tech",
                       "Fashion", "Lifestyle", "Collectibles",
                       "Misc", "Artisan", "Active"],
    "avg_platform_fee": [0.10, 0.12, 0.10, 0.08, 
                         0.10, 0.11, 0.13,
                         0.10, 0.15, 0.11]
})

In [49]:
# Left join - attach category metadata to listings 
df_enriched = pd.merge(df, cat_meta, on="main_category", how="left")

In [50]:
print("Original shape:", df.shape)
print("Enriched shape:", df_enriched.shape)
print("\nNew columns:", [c for c in df_enriched.columns if c not in df.columns])
print("\nSample:\n", df_enriched[["name", "main_category", "market_segment", "avg_platform_fee"]].head(10))
print("\nUnmatched categories (NaN market_segment):")
print(df_enriched[df_enriched["market_segment"].isnull()]["main_category"].value_counts())

Original shape: (1476202, 13)
Enriched shape: (1476202, 15)

New columns: ['market_segment', 'avg_platform_fee']

Sample:
                                      name           main_category  \
0     MLB Cincinnati Reds T Shirt Size XL                     Men
1        Razer BlackWidow Chroma Keyboard             Electronics
2                          AVA-VIV Blouse                   Women
3                   Leather Horse Statues                    Home
4                    24K GOLD plated rose                   Women
5        Bundled items requested for Ruie                   Women
6      Acacia pacific tides santorini top                   Women
7    Girls cheer and tumbling bundle of 7       Sports & Outdoors
8                   Girls Nike Pro shorts       Sports & Outdoors
9  Porcelain clown doll checker pants VTG  Vintage & Collectibles

  market_segment  avg_platform_fee
0        Fashion              0.10
1           Tech              0.08
2        Fashion              0.10
3      Lifestyle              0.11
4        Fashion              0.10
5        Fashion              0.10
6        Fashion              0.10
7         Active              0.11
8         Active              0.11
9   Collectibles              0.13

Unmatched categories (NaN market_segment):
Series([], Name: count, dtype: int64)

# pivot_table & crosstab

---------------------- PIVOT TABLE ANALYSIS -------------------------------------------

In [52]:
# Avg price per main_category x shipping
print("=== Avg Price: Category x Shipping ===")
pt1 = pd.pivot_table(df, values="price",
                    index="main_category",
                    columns="shipping",
                    aggfunc="mean",
                    fill_value=0).round(2)
pt1

=== Avg Price: Category x Shipping ===

shipping                    0      1
main_category
Beauty                  23.73  17.08
Electronics             47.78  26.20
Handmade                25.59  13.44
Home                    27.21  17.82
Kids                    23.18  16.98
Men                     36.14  31.98
Other                   25.30  16.92
Sports & Outdoors       28.38  21.95
Vintage & Collectibles  33.52  22.44
Women                   30.63  26.18

In [53]:
# Avg Price per main_category x condition_label
print("=== Avg Price: Category x Condition ===")
pt2 = pd.pivot_table(df, values="price",
                    index="main_category",
                    columns="condition_label",
                    aggfunc="mean",
                    fill_value=0).round(2)
pt2

=== Avg Price: Category x Condition ===

condition_label          Fair   Good  Like New    New   Poor
main_category
Beauty                  15.02  19.28     19.59  19.81  13.08
Electronics             41.31  42.29     46.24  23.56  40.36
Handmade                18.93  24.73     21.74  15.38  14.29
Home                    16.63  20.81     21.72  26.44  19.92
Kids                    17.58  19.79     20.35  22.13  22.58
Men                     28.49  30.08     34.44  41.42  26.04
Other                   20.44  21.52     22.44  20.14  23.02
Sports & Outdoors       22.14  27.05     27.59  23.86  23.35
Vintage & Collectibles  30.49  31.15     25.43  25.37  27.20
Women                   22.46  26.49     27.57  32.75  22.55

In [54]:
# Item count per main_category x shipping
print("\n Item Count: Category x Shipping ===")
ct1 = pd.crosstab(df["main_category"], df["shipping"])
ct1

 Item Count: Category x Shipping ===

shipping                     0       1
main_category
Beauty                   81124  126703
Electronics              51017   71672
Handmade                 11962   18880
Home                     48549   19322
Kids                    101433   70255
Men                      61503   32177
Other                    21044   24307
Sports & Outdoors        14124   11218
Vintage & Collectibles   20570   25960
Women                   404085  260297

In [55]:
# Shipping rate per category (what % of items have seller shipping)
print("\n=== Shipping Rate per Category ===")
ct2 = pd.crosstab(df["main_category"], df["shipping"], normalize="index").round(3)
ct2

=== Shipping Rate per Category ===

shipping                    0      1
main_category
Beauty                  0.390  0.610
Electronics             0.416  0.584
Handmade                0.388  0.612
Home                    0.715  0.285
Kids                    0.591  0.409
Men                     0.657  0.343
Other                   0.464  0.536
Sports & Outdoors       0.557  0.443
Vintage & Collectibles  0.442  0.558
Women                   0.608  0.392

In [ ]:
# Full Summary with margins
print("\n=== Full Summary with Totals ===")
pt3 =